### ISSUE TITLE
No npc

### ISSUE THREAD

**Issue by ivegotthis** [MaDHouSe79/mh-npcservices#4]
Hi, i have no clue what's happening here but when i call any one of the npc, they never arrive. The ambulance sometimes can be seen but that goes the wrong way.
There's no error in either the client or server console, so i'm at a lost.

**Comment by BallisticOK** [comment]
im getting the same problem

**Comment by MaDHouSe79** [comment]
just update the code, please check if it work now for you, sorry that it look to long i have been very bizy at the moment.

**Comment by ivegotthis** [comment]
Hi, thanks for this. I have only tried the Ambulance atm but there is a small problem, they do now come to you and how they grab you and put you into the ambulance is great but when we get to pillbox, i fall through the map.
This might not be a fault as i have Gabs pillbox in and just need to change the bed coords, but i don't know if they are trying to get me out of the ambulance that causes me to fall through the map or if they're teleporting me to a bed that isn't there
Thanks.

**Comment by MaDHouSe79** [comment]
> Hi, thanks for this. I have only tried the Ambulance atm but there is a small problem, they do now come to you and how they grab you and put you into the ambulance is great but when we get to pillbox, i fall through the map. This might not be a fault as i have Gabs pillbox in and just need to change the bed coords, but i don't know if they are trying to get me out of the ambulance that causes me to fall through the map or if they're teleporting me to a bed that isn't there Thanks.

To replace the checkin for the ambulance you than check this line
https://github.com/MaDHouSe79/mh-npcservices/blob/a90409ec55eb1df11d763f9f381f04412f090706/config.lua#L66


To edit the beds locations for gabs, you go and change the locations here.
https://github.com/qbcore-framework/qb-ambulancejob/blob/e9b5cc2760d548c4c00708f8ed404409f119b406/config.lua#L68

**Comment by ivegotthis** [comment]
You beat me to it, i just watched your video linked in the readme file and i saw how it works. Thanks for the reply.
