### ISSUE TITLE
For other players

### ISSUE THREAD

**Issue by ivegotthis** [MaDHouSe79/mh-npcservices#7]
I made sure it was enabled in the config but still not able to call services for other players. Thanks

**Comment by MaDHouSe79** [comment]
Yes i turn that off cause player will abuse it, and for a good RP server that's not a very good idea to have. ;)
i will change it, so you can only call players neerby, but i have to see if i have the time for that.

**Comment by ivegotthis** [comment]
Funny you should say that as that was what we were doing in the test server. thanks for the reply.

**Comment by MaDHouSe79** [comment]
lol, i was testing this script on a live server with about 15 players, and when new players came in they allways do that, and if, for example, as a player you have a chase, you can suddenly be taken away by an ems, and the players I tested it with were not really happy with that haha, they could laugh about it, but it can ruin the rp.
