### ISSUE TITLE
i got problem with when the docotor come

### ISSUE THREAD

**Issue by asmai4d** [MaDHouSe79/mh-npcservices#8]
i got problem with when the docotor come he escort the player and he put in the car the car not mov stuck and when some one escort me from the car the npc car move in

**Comment by asmai4d** [comment]
please if u have discord

**Comment by MaDHouSe79** [comment]
Reply post 1:
I don't quite understand what you mean, can you make a video so I can see what happens? 

Reply post 2:
No, sorry, I don't have a discord server.

**Comment by asmai4d** [comment]
> Owner

ok i will upload the vedio and show you what i mean https://streamable.com/ijokq4

**Comment by asmai4d** [comment]
the car not move

**Comment by asmai4d** [comment]
and there no error

**Comment by MaDHouSe79** [comment]
I just install the script new from here, but it works here, the doctor comes to pick me up and take me to the hospital.
